const paises = {
    "África do Sul":                          { pais: "África do Sul",           codigo: "za" },
    "AIK":                                    { pais: "Suécia",                  codigo: "se" },
    "Ajax":                                   { pais: "Holanda",                 codigo: "nl" },
    "Al-Ahli":                                { pais: "Arábia Saudita",          codigo: "sa" },
    "Al-Hilal":                               { pais: "Arábia Saudita",          codigo: "sa" },
    "Alajuelense":                            { pais: "Costa Rica",              codigo: "cr" },
    "Alianza Lima":                           { pais: "Peru",                    codigo: "pe" },
    "Alliancen":                              { pais: "Dinamarca",               codigo: "dk" },
    "América de Cali":                        { pais: "Colômbia",                codigo: "co" },
    "América-MEX":                            { pais: "México",                  codigo: "mx" },
    "Anderlecht":                             { pais: "Bélgica",                 codigo: "be" },
    "Angers":                                 { pais: "França",                  codigo: "fr" },
    "Argélia":                                { pais: "Argélia",                 codigo: "dz" },
    "Argentina":                              { pais: "Argentina",               codigo: "ar" },
    "Argentino":                              { pais: "Argentina",               codigo: "ar" },
    "Arsenal":                                { pais: "Inglaterra",              codigo: "gb-eng" },
    "Aruba":                                  { pais: "Aruba",                   codigo: "aw" },
    "Ascoli":                                 { pais: "Itália",                  codigo: "it" },
    "Asturias":                               { pais: "México",                  codigo: "mx" },
    "Athletic Bilbao":                        { pais: "Espanha",                 codigo: "es" },
    "Atlante":                                { pais: "México",                  codigo: "mx" },
    "Atlas":                                  { pais: "México",                  codigo: "mx" },
    "Atlético Chalaco":                       { pais: "Peru",                    codigo: "pe" },
    "Atlético de Madrid":                     { pais: "Espanha",                 codigo: "es" },
    "Atlético Marte":                         { pais: "México",                  codigo: "mx" },
    "Atlético Nacional":                      { pais: "Colômbia",                codigo: "co" },
    "Audax Italiano":                         { pais: "Chile",                   codigo: "cl" },
    "Aurora":                                 { pais: "Bolívia",                 codigo: "bo" },
    "Áustria":                                { pais: "Áustria",                 codigo: "at" },
    "Austria Wien":                           { pais: "Áustria",                 codigo: "at" },
    "Auxerre":                                { pais: "França",                  codigo: "fr" },
    "Baník Ostrava":                          { pais: "República Tcheca",        codigo: "cz" },
    "Barcelona":                              { pais: "Espanha",                 codigo: "es" },
    "Barcelona de Guayaquil":                 { pais: "Equador",                 codigo: "ec" },
    "Bayern de Munique":                      { pais: "Alemanha",                codigo: "de" },
    "Benfica":                                { pais: "Portugal",                codigo: "pt" },
    "Besiktas":                               { pais: "Turquia",                 codigo: "tr" },
    "Blooming":                               { pais: "Bolívia",                 codigo: "bo" },
    "Boca Juniors":                           { pais: "Argentina",               codigo: "ar" },
    "Bolívar":                                { pais: "Bolívia",                 codigo: "bo" },
    "Borussia Monchengladbach":               { pais: "Alemanha",                codigo: "de" },
    "Brentford":                              { pais: "Inglaterra",              codigo: "gb-eng" },
    "Budapest Honvéd":                        { pais: "Hungria",                 codigo: "hu" },
    "Burnley":                                { pais: "Inglaterra",              codigo: "gb-eng" },
    "Cádiz":                                  { pais: "Espanha",                 codigo: "es" },
    "Camarões":                               { pais: "Camarões",                codigo: "cm" },
    "Carabobo":                               { pais: "Venezuela",               codigo: "ve" },
    "Caracas":                                { pais: "Venezuela",               codigo: "ve" },
    "Cardiff City":                           { pais: "País de Gales",           codigo: "gb-wls" },
    "Cartaginés":                             { pais: "Costa Rica",              codigo: "cr" },
    "Celta de Vigo":                          { pais: "Espanha",                 codigo: "es" },
    "Centro Gallego":                         { pais: "Cuba",                    codigo: "cu" },
    "Cerezo Osaka":                           { pais: "Japão",                   codigo: "jp" },
    "Cerro Porteño":                          { pais: "Paraguai",                codigo: "py" },
    "César Vallejo":                          { pais: "Peru",                    codigo: "pe" },
    "Charleroi":                              { pais: "Bélgica",                 codigo: "be" },
    "Charlton Athletic":                      { pais: "Inglaterra",              codigo: "gb-eng" },
    "Chile":                                  { pais: "Chile",                   codigo: "cl" },
    "Chivas Guadalajara":                     { pais: "México",                  codigo: "mx" },
    "Chur":                                   { pais: "Suíça",                   codigo: "ch" },
    "Colo-Colo":                              { pais: "Chile",                   codigo: "cl" },
    "Combinado Bayern-1860":                  { pais: "Alemanha",                codigo: "de" },
    "Combinado de Caracas":                   { pais: "Venezuela",               codigo: "ve" },
    "Combinado de Curaçau":                   { pais: "Curaçao",                 codigo: "cw" },
    "Combinado de Gotemburgo":                { pais: "Suécia",                  codigo: "se" },
    "Combinado de Malmö/Norrköping":          { pais: "Suécia",                  codigo: "se" },
    "Combinado de Umeaa":                     { pais: "Suécia",                  codigo: "se" },
    "Combinado Dep. Municipal/Sp. Cristal":   { pais: "Peru",                    codigo: "pe" },
    "Combinado España/Asturias":              { pais: "Espanha",                 codigo: "es" },
    "Combinado Guadalajara/Oro":              { pais: "México",                  codigo: "mx" },
    "Combinado Hispano/St. Mary's Celtic":    { pais: "Estados Unidos",          codigo: "us" },
    "Combinado Honvéd/Kinizsi":               { pais: "Hungria",                 codigo: "hu" },
    "Combinado Juventus/Torino":              { pais: "Itália",                  codigo: "it" },
    "Combinado Loyola/La Salle":              { pais: "Venezuela",               codigo: "ve" },
    "Combinado Mariscal Sucre/Alianza Lima":  { pais: "Peru",                    codigo: "pe" },
    "Combinado PSG/Marseille":                { pais: "França",                  codigo: "fr" },
    "Combinado Sithoc/Jong Holland":          { pais: "Curaçao",                 codigo: "cw" },
    "Comunicaciones":                         { pais: "Guatemala",               codigo: "gt" },
    "Congo":                                  { pais: "Congo",                   codigo: "cg" },
    "Córdoba":                                { pais: "Espanha",                 codigo: "es" },
    "Coreia do Sul":                          { pais: "Coreia do Sul",           codigo: "kr" },
    "Costa do Marfim":                        { pais: "Costa do Marfim",         codigo: "ci" },
    "Costa Rica":                             { pais: "Costa Rica",              codigo: "cr" },
    "Cruz Azul Hidalgo":                      { pais: "México",                  codigo: "mx" },
    "Cruzador Amethyst":                      { pais: "Reino Unido",             codigo: "gb" },
    "Cruzador Argyll":                        { pais: "Reino Unido",             codigo: "gb" },
    "Crystal Palace":                         { pais: "Inglaterra",              codigo: "gb-eng" },
    "Cuba":                                   { pais: "Cuba",                    codigo: "cu" },
    "Curaçao":                                { pais: "Curaçao",                 codigo: "cw" },
    "Defensa y Justicia":                     { pais: "Argentina",               codigo: "ar" },
    "Defensor Lima":                          { pais: "Peru",                    codigo: "pe" },
    "Deportes Quindío":                       { pais: "Colômbia",                codigo: "co" },
    "Deportivo Cali":                         { pais: "Colômbia",                codigo: "co" },
    "Deportivo Italia":                       { pais: "Venezuela",               codigo: "ve" },
    "Deportivo La Coruña":                    { pais: "Espanha",                 codigo: "es" },
    "Deportivo Municipal":                    { pais: "Peru",                    codigo: "pe" },
    "Deportivo Quito":                        { pais: "Equador",                 codigo: "ec" },
    "Dínamo Zagreb":                          { pais: "Croácia",                 codigo: "hr" },
    "Dublin":                                 { pais: "Irlanda",                 codigo: "ie" },
    "Dynamo de Kiev":                         { pais: "Ucrânia",                 codigo: "ua" },
    "El Salvador":                            { pais: "El Salvador",             codigo: "sv" },
    "Emelec":                                 { pais: "Equador",                 codigo: "ec" },
    "Emirados Árabes Unidos":                 { pais: "Emirados Árabes Unidos",  codigo: "ae" },
    "Encouraçado Moreno":                     { pais: "Argentina",               codigo: "ar" },
    "Encouraçado Renown":                     { pais: "Reino Unido",             codigo: "gb" },
    "Equador":                                { pais: "Equador",                 codigo: "ec" },
    "Espanyol":                               { pais: "Espanha",                 codigo: "es" },
    "Estados Unidos":                         { pais: "Estados Unidos",          codigo: "us" },
    "Estrela Vermelha":                       { pais: "Sérvia",                  codigo: "rs" },
    "Estudiantes":                            { pais: "Argentina",               codigo: "ar" },
    "Everest":                                { pais: "Equador",                 codigo: "ec" },
    "Everton":                                { pais: "Inglaterra",              codigo: "gb-eng" },
    "Everton de Viña del Mar":                { pais: "Chile",                   codigo: "cl" },
    "FAS":                                    { pais: "El Salvador",             codigo: "sv" },
    "Fenerbahçe":                             { pais: "Turquia",                 codigo: "tr" },
    "Ferencváros":                            { pais: "Hungria",                 codigo: "hu" },
    "Feyenoord":                              { pais: "Holanda",                 codigo: "nl" },
    "Finlândia":                              { pais: "Finlândia",               codigo: "fi" },
    "First Vienna":                           { pais: "Áustria",                 codigo: "at" },
    "Fortuna '54":                            { pais: "Holanda",                 codigo: "nl" },
    "Fulham":                                 { pais: "Inglaterra",              codigo: "gb-eng" },
    "Goréenne":                               { pais: "Senegal",                 codigo: "sn" },
    "Grasshopper":                            { pais: "Suíça",                   codigo: "ch" },
    "Groningen":                              { pais: "Holanda",                 codigo: "nl" },
    "Guarani-PAR":                            { pais: "Paraguai",                codigo: "py" },
    "Guiana Francesa":                        { pais: "Guiana Francesa",         codigo: "gf" },
    "Hajduk Split":                           { pais: "Croácia",                 codigo: "hr" },
    "Herediano":                              { pais: "Costa Rica",              codigo: "cr" },
    "Hibernian":                              { pais: "Escócia",                 codigo: "gb-sct" },
    "Holanda":                                { pais: "Holanda",                 codigo: "nl" },
    "Honduras":                               { pais: "Honduras",                codigo: "hn" },
    "Huelva":                                 { pais: "Espanha",                 codigo: "es" },
    "Huracán":                                { pais: "Argentina",               codigo: "ar" },
    "Iberia":                                 { pais: "Cuba",                    codigo: "cu" },
    "IFK Norrkoping":                         { pais: "Suécia",                  codigo: "se" },
    "Independiente":                          { pais: "Argentina",               codigo: "ar" },
    "Independiente Del Valle":                { pais: "Equador",                 codigo: "ec" },
    "Independiente Medellín":                 { pais: "Colômbia",                codigo: "co" },
    "Independiente Petrolero":                { pais: "Bolívia",                 codigo: "bo" },
    "Independiente Rivadavia":                { pais: "Argentina",               codigo: "ar" },
    "Independiente Santa Fé":                 { pais: "Colômbia",                codigo: "co" },
    "Iraque":                                 { pais: "Iraque",                  codigo: "iq" },
    "Jamaica":                                { pais: "Jamaica",                 codigo: "jm" },
    "Japão":                                  { pais: "Japão",                   codigo: "jp" },
    "Jeanne d'Arc":                           { pais: "Senegal",                 codigo: "sn" },
    "JEF United Ichihara":                    { pais: "Japão",                   codigo: "jp" },
    "Jorge Wilstermann":                      { pais: "Bolívia",                 codigo: "bo" },
    "Júbilo Iwata":                           { pais: "Japão",                   codigo: "jp" },
    "Junior Barranquilla":                    { pais: "Colômbia",                codigo: "co" },
    "Juventud Asturiana":                     { pais: "Cuba",                    codigo: "cu" },
    "Juventus":                               { pais: "Itália",                  codigo: "it" },
    "Karlsruhe":                              { pais: "Alemanha",                codigo: "de" },
    "Koln":                                   { pais: "Alemanha",                codigo: "de" },
    "Kuwait":                                 { pais: "Kuwait",                  codigo: "kw" },
    "KV Mechelen":                            { pais: "Bélgica",                 codigo: "be" },
    "La Salle":                               { pais: "Venezuela",               codigo: "ve" },
    "LDU":                                    { pais: "Equador",                 codigo: "ec" },
    "Le Havre":                               { pais: "França",                  codigo: "fr" },
    "Leeds United":                           { pais: "Inglaterra",              codigo: "gb-eng" },
    "Lens":                                   { pais: "França",                  codigo: "fr" },
    "Leo Victor":                             { pais: "Suriname",                codigo: "sr" },
    "León":                                   { pais: "México",                  codigo: "mx" },
    "Lille":                                  { pais: "França",                  codigo: "fr" },
    "Litoral":                                { pais: "Bolívia",                 codigo: "bo" },
    "Maccabi Netanya":                        { pais: "Israel",                  codigo: "il" },
    "Magallanes":                             { pais: "Chile",                   codigo: "cl" },
    "Málaga":                                 { pais: "Espanha",                 codigo: "es" },
    "Mali":                                   { pais: "Mali",                    codigo: "ml" },
    "Malmo":                                  { pais: "Suécia",                  codigo: "se" },
    "Martinica":                              { pais: "Martinica",               codigo: "mq" },
    "Melgar":                                 { pais: "Peru",                    codigo: "pe" },
    "México":                                 { pais: "México",                  codigo: "mx" },
    "Milan":                                  { pais: "Itália",                  codigo: "it" },
    "Millonarios":                            { pais: "Colômbia",                codigo: "co" },
    "Minervén":                               { pais: "Venezuela",               codigo: "ve" },
    "Monarcas Morelia":                       { pais: "México",                  codigo: "mx" },
    "Monterrey":                              { pais: "México",                  codigo: "mx" },
    "Murcia":                                 { pais: "Espanha",                 codigo: "es" },
    "Nacional de Rosário":                    { pais: "Argentina",               codigo: "ar" },
    "Nacional Potosí":                        { pais: "Bolívia",                 codigo: "bo" },
    "Nacional-PAR":                           { pais: "Paraguai",                codigo: "py" },
    "Nacional-URU":                           { pais: "Uruguai",                 codigo: "uy" },
    "Nancy":                                  { pais: "França",                  codigo: "fr" },
    "Nantes":                                 { pais: "França",                  codigo: "fr" },
    "Napoli":                                 { pais: "Itália",                  codigo: "it" },
    "Necaxa":                                 { pais: "México",                  codigo: "mx" },
    "Newcastle":                              { pais: "Inglaterra",              codigo: "gb-eng" },
    "Nottingham Forest":                      { pais: "Inglaterra",              codigo: "gb-eng" },
    "Nurnberg":                               { pais: "Alemanha",                codigo: "de" },
    "Olimpia":                                { pais: "Paraguai",                codigo: "py" },
    "Olympiacos":                             { pais: "Grécia",                  codigo: "gr" },
    "Orgryte IS":                             { pais: "Suécia",                  codigo: "se" },
    "Oriente Petrolero":                      { pais: "Bolívia",                 codigo: "bo" },
    "Oro":                                    { pais: "México",                  codigo: "mx" },
    "Pachuca":                                { pais: "México",                  codigo: "mx" },
    "Panamá":                                 { pais: "Panamá",                  codigo: "pa" },
    "Panathinaikos":                          { pais: "Grécia",                  codigo: "gr" },
    "Paris Saint-Germain":                    { pais: "França",                  codigo: "fr" },
    "Partizan":                               { pais: "Sérvia",                  codigo: "rs" },
    "Patronato":                              { pais: "Argentina",               codigo: "ar" },
    "Peñarol":                                { pais: "Uruguai",                 codigo: "uy" },
    "Peterborough United":                    { pais: "Inglaterra",              codigo: "gb-eng" },
    "Petro Atlético":                         { pais: "Angola",                  codigo: "ao" },
    "Plymouth Argyle":                        { pais: "Inglaterra",              codigo: "gb-eng" },
    "Pohang Steelers":                        { pais: "Coreia do Sul",           codigo: "kr" },
    "Porto":                                  { pais: "Portugal",                codigo: "pt" },
    "Portsmouth":                             { pais: "Inglaterra",              codigo: "gb-eng" },
    "Portugal":                               { pais: "Portugal",                codigo: "pt" },
    "Presidente Hayes":                       { pais: "Paraguai",                codigo: "py" },
    "Puebla":                                 { pais: "México",                  codigo: "mx" },
    "Puntarenas":                             { pais: "Costa Rica",              codigo: "cr" },
    "Racing":                                 { pais: "Argentina",               codigo: "ar" },
    "Racing Club-CAR":                        { pais: "Guadalupe",               codigo: "gp" },
    "Racing Paris":                           { pais: "França",                  codigo: "fr" },
    "Racing-URU":                             { pais: "Uruguai",                 codigo: "uy" },
    "Rangers":                                { pais: "Escócia",                 codigo: "gb-sct" },
    "Real Club España":                       { pais: "México",                  codigo: "mx" },
    "Real Madrid":                            { pais: "Espanha",                 codigo: "es" },
    "Real Oviedo":                            { pais: "Espanha",                 codigo: "es" },
    "Reggina":                                { pais: "Itália",                  codigo: "it" },
    "Reims":                                  { pais: "França",                  codigo: "fr" },
    "River Plate":                            { pais: "Argentina",               codigo: "ar" },
    "Robinhood":                              { pais: "Suriname",                codigo: "sr" },
    "Roma":                                   { pais: "Itália",                  codigo: "it" },
    "Romênia":                                { pais: "Romênia",                 codigo: "ro" },
    "Rot-Weiss Essen":                        { pais: "Alemanha",                codigo: "de" },
    "Saarbrucken":                            { pais: "Alemanha",                codigo: "de" },
    "Saint-Étienne":                          { pais: "França",                  codigo: "fr" },
    "Salernitana":                            { pais: "Itália",                  codigo: "it" },
    "San José":                               { pais: "Bolívia",                 codigo: "bo" },
    "San Lorenzo":                            { pais: "Argentina",               codigo: "ar" },
    "Santiago Morning":                       { pais: "Chile",                   codigo: "cl" },
    "Santiago Wanderers":                     { pais: "Chile",                   codigo: "cl" },
    "Saprissa":                               { pais: "Costa Rica",              codigo: "cr" },
    "Seattle Sounders":                       { pais: "Estados Unidos",          codigo: "us" },
    "Sedan":                                  { pais: "França",                  codigo: "fr" },
    "Seleção da Antuérpia":                   { pais: "Bélgica",                 codigo: "be" },
    "Seleção de Caiena":                      { pais: "Guiana Francesa",         codigo: "gf" },
    "Seleção de Jalisco":                     { pais: "México",                  codigo: "mx" },
    "Seleção de Kobe":                        { pais: "Japão",                   codigo: "jp" },
    "Seleção de Mérida":                      { pais: "México",                  codigo: "mx" },
    "Seleção de Quito":                       { pais: "Equador",                 codigo: "ec" },
    "Seleção de Ulsan":                       { pais: "Coreia do Sul",           codigo: "kr" },
    "Seleção Lomé 1":                         { pais: "Togo",                    codigo: "tg" },
    "Servette":                               { pais: "Suíça",                   codigo: "ch" },
    "Sevilla":                                { pais: "Espanha",                 codigo: "es" },
    "Shandong Luneng":                        { pais: "China",                   codigo: "cn" },
    "Shonan Bellmare":                        { pais: "Japão",                   codigo: "jp" },
    "Síria":                                  { pais: "Síria",                   codigo: "sy" },
    "Slavia Praga":                           { pais: "República Tcheca",        codigo: "cz" },
    "Slovan Bratislava":                      { pais: "Eslováquia",              codigo: "sk" },
    "Sol de America":                         { pais: "Paraguai",                codigo: "py" },
    "Southampton":                            { pais: "Inglaterra",              codigo: "gb-eng" },
    "Sparta Praga":                           { pais: "República Tcheca",        codigo: "cz" },
    "Spartak Trnava":                         { pais: "Eslováquia",              codigo: "sk" },
    "Sport Boys":                             { pais: "Peru",                    codigo: "pe" },
    "Sporting":                               { pais: "Portugal",                codigo: "pt" },
    "Sporting Cristal":                       { pais: "Peru",                    codigo: "pe" },
    "Sporting de Gijón":                      { pais: "Espanha",                 codigo: "es" },
    "St. Louis Shamrocks":                    { pais: "Estados Unidos",          codigo: "us" },
    "Stabaek":                                { pais: "Noruega",                 codigo: "no" },
    "Staenet":                                { pais: "Dinamarca",               codigo: "dk" },
    "Stafa":                                  { pais: "Suíça",                   codigo: "ch" },
    "Standard de Liège":                      { pais: "Bélgica",                 codigo: "be" },
    "Tchecoslováquia":                        { pais: "Tchecoslováquia",         codigo: "cz" },
    "Tenerife":                               { pais: "Espanha",                 codigo: "es" },
    "The Strongest":                          { pais: "Bolívia",                 codigo: "bo" },
    "Toluca":                                 { pais: "México",                  codigo: "mx" },
    "Toulouse":                               { pais: "França",                  codigo: "fr" },
    "Transvaal":                              { pais: "Suriname",                codigo: "sr" },
    "Troyes":                                 { pais: "França",                  codigo: "fr" },
    "ÚDA de Praga":                           { pais: "República Tcheca",        codigo: "cz" },
    "Újpest":                                 { pais: "Hungria",                 codigo: "hu" },
    "UNAM Pumas":                             { pais: "México",                  codigo: "mx" },
    "União da Madeira":                       { pais: "Portugal",                codigo: "pt" },
    "União Soviética":                        { pais: "União Soviética",         codigo: "ru" },
    "Unión Española":                         { pais: "Chile",                   codigo: "cl" },
    "Universidad Autónoma":                   { pais: "México",                  codigo: "mx" },
    "Universidad Católica":                   { pais: "Chile",                   codigo: "cl" },
    "Universidad Central":                    { pais: "Venezuela",               codigo: "ve" },
    "Universidad de Chile":                   { pais: "Chile",                   codigo: "cl" },
    "Universidad Nacional-CO":                { pais: "Colômbia",                codigo: "co" },
    "Universitario":                          { pais: "Peru",                    codigo: "pe" },
    "Uruguai":                                { pais: "Uruguai",                 codigo: "uy" },
    "Valdez":                                 { pais: "Equador",                 codigo: "ec" },
    "Valencia":                               { pais: "Espanha",                 codigo: "es" },
    "Veracruz":                               { pais: "México",                  codigo: "mx" },
    "Vietnã":                                 { pais: "Vietnã",                  codigo: "vn" },
    "Viking":                                 { pais: "Noruega",                 codigo: "no" },
    "Vitória de Guimarães":                   { pais: "Portugal",                codigo: "pt" },
    "Vojvodina":                              { pais: "Sérvia",                  codigo: "rs" },
    "Werder Bremen":                          { pais: "Alemanha",                codigo: "de" },
    "West Ham":                               { pais: "Inglaterra",              codigo: "gb-eng" },
    "Willem II":                              { pais: "Holanda",                 codigo: "nl" },
    "Young Boys":                             { pais: "Suíça",                   codigo: "ch" },
    "Zacatepec":                              { pais: "México",                  codigo: "mx" },
    "Zamalek":                                { pais: "Egito",                   codigo: "eg" },
};

export default paises;
